export { default as About } from "./About/About";
export { default as AtticProfile } from "./AtticProfile/AtticProfile";
export { default as Home } from "./Home/Home";
export { default as Locations } from "./Locations/Locations";
export { default as LoginPage } from "./LoginPage/LoginPage";
export { default as Patches } from "./Patches/Patches";
export { default as Profile } from "./Profile/Profile";
export { default as Shop } from "./Shop/Shop";
export { default as Cart } from "./Cart/Cart";
export { default as Item} from "./Shop/Item";
export { default as Patch } from "./Patches/Patch";
export { default as Checkout } from "./Cart/Checkout";